name: Playwright Tests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:
    inputs:
      update_snaphosts:
        required: true
        type: choice
        default: "false"
        options:
          - "false"
          - "true"
      upload_artifact:
        required: true
        type: choice
        default: "false"
        options:
          - "false"
          - "true"

    # 현재는 일단 직접 실행
    # push:
    #   branches: [main, master]
    # pull_request:
    #   branches: [main, master]

jobs:
  playwright:
    name: "Playwright Tests"
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.27.0-focal
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: npm ci
      - name: Run your tests
        run: npx playwright test
